### PR TITLE
WIP: Debian AppImage fixes

### PR DESCRIPTION
**Pull request by lpinner**
The PR is a work in progress for comment.  

The binary attached below was built on Ubuntu 20.04 and tested on Fedora 39, Ubuntu 23.10, 22.04 and Ubuntu 20.04 and runs successfully on all.

[ChordPro-6.050_021 (20.04).zip](https://github.com/ChordPro/chordpro/files/14829282/ChordPro-6.050_021.20.04.zip)

I also modified the pp/linux/AppRun file to allow calling cli chordpro from the AppImage, e.g.
```
$ ./ChordPro-6.050_021.AppImage chordpro -A

ChordPro: A lyrics and chords formatting program.

ChordPro will read a text file containing the lyrics of one or many
songs plus chord information. ChordPro will then generate a
photo-ready, professional looking, impress-your-friends sheet-music
suitable for printing on your nearest printer.

To learn more about ChordPro, look for the man page or do
"chordpro --help" for the list of options.

For more information, see https://www.chordpro.org .

Run-time information:
  ChordPro core          6.050_021  (Unsupported development snapshot)
  Perl                   v5.34.0    (/tmp/.mount_ChordPLmFBCD/chordpro)
  AppImage Packager      1.00      
  Resource path          ~/.config/chordpro
                         /tmp/.mount_ChordPLmFBCD/lib/ChordPro/res
  ABC support            QuickJS_XS (ABC2SVG version v1.22.14 of 2024-03-03)

Modules and libraries:
  Storable               3.25      
  Object::Pad            0.79      
  Text::Layout           0.035     
  HarfBuzz::Shaper       0.026     
  HarfBuzz library       2.6.4i    
  File::LoadLines        1.046     
  PDF::API2              2.045     
  SVGPDF                 0.086.2   
  Font::TTF              1.06      
  JavaScript::QuickJS    0.19      
```
The packages and toolchain required was:
```
sudo apt install libwx-perl cpanminus liblocal-lib-perl libgtk-3-dev libperl-dev libdeflate0 libsdl2-2.0-0 patchelf
wget -O appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
chmod u+x appimagetool
export PATH=.:$PATH
```

### CODE REVIEW

**Comment by sciurius** [comment]
I can confirm that the appimage from [ChordPro-6.050_021.zip](https://github.com/ChordPro/chordpro/files/14769152/ChordPro-6.050_021.zip) runs on Fedora 39 and Linux Mint 21.2. That looks great.

**Comment by sciurius** [comment]
It would be very nice if this could be made to work when building on 20.04.

**Comment by lpinner** [comment]
> It would be very nice if this could be made to work when building on 20.04.

I've tried 18.04 and 20.04 and played around with switching the order of the libs in the ${CC} command but keep getting linker errors. I don't really know what I'm doing though, just googling the errors and trying variations. Do you have any suggestions?

**Comment by lpinner** [comment]
Managed to get it to build on 20.04 and the attached AppImage runs on Fedora 39 
[ChordPro-6.050_021 (20.04).zip](https://github.com/ChordPro/chordpro/files/14829282/ChordPro-6.050_021.20.04.zip)

**Comment by lpinner** [comment]
The commit history has gotten messy. I have a clean branch that's up to date with dev with my changes. Would you like a fresh PR?

**Comment by sciurius** [comment]
Yes, a new, clean PR would be nice ;)

**Pull request closed without merging**
