### PR TITLE
(website) Update macOS documentation

### PR DESCRIPTION
**Pull request by Desbeers**

### CODE REVIEW

**Comment by sciurius** [comment]
I think anchors are now gone completely.
There are sites that show an anchor for copying only when you hover the topic. Can you achieve that?

**Comment by Desbeers** [comment]
> I think anchors are now gone completely.

Strange... Looks like the https://www.chordpro.org/beta/ is only partly updated. Its still using the previous `site.css` (so still hiding all anchors) `head.html` should now conditionally add some CSS to hide anchors for the stable docs only.

> There are sites that show an anchor for copying only when you hover the topic. Can you achieve that?

I’ll have a look...

**Comment by sciurius** [comment]
I see in `assets/css/site.css` that `heading-anchor` gets `display:none`, and in `layouts/partials/head.html` that `heading-anchor` gets `display:none` for stable.

**Comment by sciurius** [comment]
I can't explain... But it seems to be okay now.

**Pull request merged**
