### PR TITLE
Tablature mostly works now.  Still consider this development, need to create test files.

### PR DESCRIPTION
**Pull request by weltyj**

### CODE REVIEW

**Comment by sciurius** [comment]
That's interesting.
I've carried the a2crd conversion one step further: ChordPro now automatically detects whether the input is **crd** and, if so, converts (internally) to **cho** before further processing. The command line option `--a2crd` merely causes the result from the internal conversion to be sent to output.

**Comment by weltyj** [comment]
Sounds good to me.   I'm making good progress on recognizing tablature and chord fingering lines.   Before I load any test files to github, I need to create sanitized versions of the files so there is no chance at all of copyright issues even for sample test input files.   I current have a sample of 17 files with a range of input formats, and chord finger charts for my test set.

In my previous life before retirement, I was a biometrician, and those old statistics keep whispering to me that a statistical approach to classifying lines as chords, comments, lyrics or tablature may be more robust yet.  It could be viewed as a bayesian like classifier that would also consider context of surrounding lines.

But I am holding off on that as the current method (not on github yet), which only analyzes one line at a time is pretty good.  No need to complicate things unless we think there's a good reason for more improvement after other users have had a chance to try it out.

I'll keep you updated.

--Jeff







On Friday, October 30, 2020, 5:29:14 AM PDT, Johan Vromans <notifications@github.com> wrote: 







That's interesting.
I've carried the a2crd conversion one step further: ChordPro now automatically detects whether the input is crd and, if so, converts (internally) to cho before further processing. The command line option --a2crd merely causes the result from the internal conversion to be sent to output.

**Comment by weltyj** [comment]
I believe I have this working well now (for roman chord names), and have commited my changes, including test files for A2Crd to github/weltyj/Chordpro/dev , but github won't give me the "Create Pull Request" green button.   It indicatess the changes are merge-able from my dev branch into the Chordpro/chordpro/dev branch.   I'll keep looking for why github isn't cooperating but for the moment I'm stuck.







On Friday, October 30, 2020, 5:29:14 AM PDT, Johan Vromans <notifications@github.com> wrote: 







That's interesting.
I've carried the a2crd conversion one step further: ChordPro now automatically detects whether the input is crd and, if so, converts (internally) to cho before further processing. The command line option --a2crd merely causes the result from the internal conversion to be sent to output.

**Comment by weltyj** [comment]
I had to close the open pull request on my dev branch before I could create a new pull request on my dev branch.

You may want to look at my regex stuff in generic_parse_chord(), decode_fingering() and classify_pct_chords() in A2Crd.pm -- whie the regex's are functional, there may be better ways to implement them for efficiency.

Hope your weekend is going well!






On Saturday, October 31, 2020, 9:16:38 AM PDT, jeff welty <weltyj@yahoo.com> wrote: 





I believe I have this working well now (for roman chord names), and have commited my changes, including test files for A2Crd to github/weltyj/Chordpro/dev , but github won't give me the "Create Pull Request" green button.   It indicatess the changes are merge-able from my dev branch into the Chordpro/chordpro/dev branch.   I'll keep looking for why github isn't cooperating but for the moment I'm stuck.







On Friday, October 30, 2020, 5:29:14 AM PDT, Johan Vromans <notifications@github.com> wrote: 







That's interesting.
I've carried the a2crd conversion one step further: ChordPro now automatically detects whether the input is crd and, if so, converts (internally) to cho before further processing. The command line option --a2crd merely causes the result from the internal conversion to be sent to output.

**Pull request closed without merging**
