### PR TITLE
2-page songalignment and sorting

### PR DESCRIPTION
**Pull request by bublath**
A new and hopefully cleaner approach.
Almost all code is in a function. Only thing outside is the adding of blank pages as this has to happen in generate_songbook() and I sort of like my "." verbose output for large songbooks.

I believe the reason why things were not working as expected before was a dependency on the pagealign setting, which I removed completely now.

### CODE REVIEW

**Comment by sciurius** [comment]
Thanks. However, I still get the same results with the test program mentioned in https://github.com/ChordPro/chordpro/pull/281#issuecomment-1589978532.

**Comment by bublath** [comment]
Strange. Looks ok for me
http://bublath.de/test.pdf
Only thing I just noticed: The empty page number 3 does not have a page number

**Comment by sciurius** [comment]
Strange.

These are the commands I use:

````
$ git clone https://github.com/bublath/chordpro.git
$ cd chordpro
$ git co pagealign
$ git status -u
On branch pagealign
Your branch is up to date with 'origin/pagealign'.

nothing to commit, working tree clean
$ perl script/chordpro.pl -X --cfg ~/tmp/pages.json --csv -o ~/tmp/x.pdf ~/tmp/pages.cho
"my" variable $page masks earlier declaration in same scope at /home/jv/tmp/chordpro/script/../lib/App/Music/ChordPro/Output/PDF.pm line 155.
$ cat ~/tmp/x.csv
title;pages
B Song1 (one page);1
A Song2 (one page);2
C Song3 (two pages);3-4
````

Your output has non-standard fonts, maybe there's something in your private config?

**Comment by bublath** [comment]
You got the wrong branch in your test. I directly put the fixes in a fork from your dev branch and discontinued the pagealign branch (deleted it now to avoid further confusion).
Did a small update as I realized that sometimes the {pages} key is not present and causes a warning and made small cosmetic changes. I recommend using "-v" in your tests. Gives you some output, e.g. it now prints a space between the dots where a blank page gets added. Nice to watch on large songbooks.
Though nothing that would influence your test case. 
Please try again checking out the "dev" branch of my fork.

Room for improvement that I see is, that in the "compact" mode, it could swap song 2 and song 3 in your example, however I did not implement a special case for the last song (it always swaps with the next and not with the previous), so in that case you'll  still get a blank page.

**Comment by sciurius** [comment]
I'm considering a couple of changes that may be helpful for your implementation.

* A `--progress` option, to show dots and spaces for progress. I will send these to STDERR, not STDOUT since STDOUT may be redirected (e.g. `chordpro ... > x.pdf`.
* `meta.padding` that goes with your `meta.pages`. If padding is set then generate_song will add `meta.padding` empty pages (or blank pages with headings/footers, see `pdf/pagealign-songs`).

So when shuffling you only need to add a `meta.padding` and the alignment will be automatic.

**Comment by bublath** [comment]
A progress option sounds nice. Verbose prints too much stuff in addition to my outputs.
I'm not sure I fully understand your meta.padding (would it tell a song, how many pages to use, regardless of the actual page utilization?), but let me know once its ready, then I can check it out and see how it might be helpful.

**Pull request closed without merging**
