### PR TITLE
Latex Pull-Request for Chordpro

### PR DESCRIPTION
**Pull request by JoeRu**
Hi Johan,
this is a first dev-test ready PR for discussion. It works pretty nicely with the provided templates. The main question open is where to store the template-files (*.tt) - root folder isn't the best place - i guess - but i didn't find a resources folder to put them nicely?
And the second question is where to search per default in the config (which sort of depends on question one)?

This draft makes use of the 
http://songs.sourceforge.net/songsdoc/songs.html
Package; But there a some more available - which i didn't tested so far. 

I didn't add testcases (yet) - because they would heavily depend on the template-files - which I rather didn't like to create as a good testcase. I'm still figuring which kind of test-cases are not that output-sensitive.

New dependencies are:
```
use Template;
use LaTeX::Encode;
```

So this are my 3-cents - I am open for discussion /  suggestions / changes:
Yours Johannes :)

### CODE REVIEW

**Comment by sciurius** [comment]
Looks nice.
I suggest to put the templates in res/templates . 

````
*** lib/App/Music/ChordPro/Output/LaTeX.pm~     2022-03-07 11:45:05.090405259 +0100
--- lib/App/Music/ChordPro/Output/LaTeX.pm      2022-03-07 12:01:22.449304560 +0100
***************
*** 31,38 ****
  
      $gcfg = $::config->{LaTeX};
  
!     $gtemplate = Template->new({
!         INCLUDE_PATH => $gcfg->{template_include_path},
          INTERPOLATE  => 1,
      }) || die "$Template::ERROR\n";
  
--- 31,40 ----
  
      $gcfg = $::config->{LaTeX};
  
!     $gtemplate = Template->new
!       ({
!       INCLUDE_PATH => [ $gcfg->{template_include_path},
!                         ::rsc_or_file("templates/"), ],
          INTERPOLATE  => 1,
      }) || die "$Template::ERROR\n";
  
````

I'm not sure it is a good idea to put all the latex stuff as separate items in the config. Maybe it is better to select the LaTeX package in the config, and then set the necessary items in de code instead?

**Comment by sciurius** [comment]
It might even be better to move all latex related config a separate config file to be placed in the config directory.

**Comment by JoeRu** [comment]
Hi Johan,

ok, enhanced it - as discussed; About the config - 
> Maybe it is better to select the LaTeX package in the config, and then set the necessary items in de code instead?

The Latex-Package isn't picked in the config - it's part of the Template. 
Or - what you are referencing about?
The default-config is about the Songs-Package - but it would be easy to adapt.

Yours,
Johannes

**Comment by sciurius** [comment]
As I understand, the choice for packge is made in `songbook.tt` (the current one uses `\usepackage[chorded]{songs}`).

However, several of the config settings seem to apply to the choice of package:

````
"newpage_tag" : "\\newpage",
"emptyline_tag" : "\\brk", 
"columnbreak_tag" : "\\columnbreak",
"beginchorus_tag" : "\\beginchorus",
"endchorus_tag" : "\\endchorus",
"beginverse_tag" : "\\beginverse",
"endverse_tag" : "\\endverse",
"begingrid_tag" : "\\begin{verbatim}",
"endgrid_tag" : "\\end{verbatim}",
"begintab_tag" : "\\begin{verbatim}",
"endtab_tag" : "\\end{verbatim}",
"gchordstart_tag" : "\\[", // for Guitar this would be fe. "\\guitarChord{"
"gchordend_tag"  : "]", // for Guitar this would be "}"
"chorded_line" : "\\chordson ", // Songs-package require this to know when to switch 
"unchorded_line" : "\\chordsoff ", // chordlines off - it will be printed ahead of a song line
"start_spaces_songline" : "\\hspace{0,5cm}", // if a songline starts with spaces it will be replaced by start_spaces_songline
````
Therefore I think it is better to move these to separate configs, for example `latex_songs_chorded.json`:
````
{ "latex" : {
   "package" : "\\usepackage[chorded]{songs}",
   "newpage_tag" : "\\newpage",
   ...
}
````
The user can then select how she wants to produce the output:

    chordpro --config latex_songs_chorded ...
    chordpro --config latex_guitar ...

and so on.

**Comment by JoeRu** [comment]
Thats a good Idea - on that way - it's possible to provide at least initial configs to the most popular packages. (Even so - not many are under any development at all).

Do you have a hint - where i should have to look on provide a path and read such a config?

**Comment by JoeRu** [comment]
I did checked and thought about this part; And it would be nice to have several configs available.
But - the Package should not be configurable in that way. It's part of the template - and sort of - are the templates itself part of the LaTeX Solution.

I would prefer to keep this as the initial push the way it is. It's sort of well tested. I will provide some tests as addon to this PR. The separate configs needed to be done sometimes else. My free time is actual over - and i can't afford much more time in the moment.

**Comment by JoeRu** [comment]
Hi Johan,
how do you like to procceed with this PR?
I feel some issues not quite technical i guess - but not sure how to solve them or to help?

yours
Johannes

------
The actual build fails are not depending on this PR 
```

Use of uninitialized value in lc at /__w/chordpro/chordpro/blib/lib/App/Music/ChordPro/Config.pm line 116.
# Files out/40_html_1.html and ref/40_html_1.html differ at line 51
#   <  <div class="verse">
#   >  <table class="songline">

#   Failed test at ./00_basic.pl line 26.
Use of uninitialized value in lc at /__w/chordpro/chordpro/blib/lib/App/Music/ChordPro/Config.pm line 116.
# Files out/40_html_2.html and ref/40_html_2.html differ at line 51
#   <  <div class="verse">
#   >  <table class="songline">

#   Failed test at ./00_basic.pl line 36.
Use of uninitialized value in lc at /__w/chordpro/chordpro/blib/lib/App/Music/ChordPro/Config.pm line 116.
# Files out/40_html_3.html and ref/40_html_3.html differ at line 39
#   <  <div class="verse">
#   >  <table class="songline">

#   Failed test at ./00_basic.pl line 46.
# Looks like you failed 3 tests of 3.
```

**Comment by sciurius** [comment]
Use of uninitialized value in lc at /__w/chordpro/chordpro/blib/lib/App/Music/ChordPro/Config.pm line 116.

This is a harmless warning and already fixed in the dev.
````
# Files out/40_html_1.html and ref/40_html_1.html differ at line 51
#   <  <div class="verse">
#   >  <table class="songline">
````
These are caused by your commit ce624d9a2e51f8009ce275690ec85d1842261038. If you force a context then you need to adapt the test cases that act on this context.

**Comment by sciurius** [comment]
As for how to proceed, I'd really like to see the issues mentioned in https://github.com/ChordPro/chordpro/pull/213#issuecomment-1061761076 taken care of.

**Comment by JoeRu** [comment]
> As for how to proceed, I'd really like to see the issues mentioned in [#213 (comment)](https://github.com/ChordPro/chordpro/pull/213#issuecomment-1061761076) taken care of.

ok; So - to be clear - shall i remove the default-config for this out of config.pm and put it as seperate json-file?

**Comment by sciurius** [comment]
My initial suggestion was to move the latex package relevant configs to a subdirectory of config, to be included on demand only, but that violates the design principle that all configuation items should have an initial value (i.e., the keys must be present in the config hash). And it turned out that's not the real problem.

Currently, you have three kinds of definitions in the LaTeX part of the config.

1. The names of the templates.
3. The template search path.
4. Settings specific for the LaTeX package being used.

**Comment by sciurius** [comment]
My initial suggestion was to move the latex package relevant configs to a subdirectory of config, to be included on demand only, but that violates the design principle that all configuation items should have an initial value (i.e., the keys must be present in the config hash). And it turned out that's not the real problem.

Currently, you have three kinds of definitions in the LaTeX part of the config.

First, the names of the templates. This is okay, people may want to customize the way their songs are rendered. This is similar to the styles files in the HTML output settings.

Second, the template search path. This should be preset to `[ ]`. In the code, please add (prepend) the elements of $ENV{CHORDPRO_LIB}  with `/templates` appended so the user can have her own set of templates.

Third, package-specific definitions for some LaTeX items. These are not independently configurable. I know that you want to abstract out much of the details but these simply do not belong in the configs.  
For example, the beginchorus_tag is `"\\beginchorus"`. This macro is defined in the LaTeX 'song' package which is included in `songbook.tt`. If I were to use the 'songbook' package I need to provide an alternative `songbook.tt` but I would **also** need to change the definition of beginchorus_tag to `"\\begin{SBChorus}"`etc. So the proper place to define these is in `songbook.tt`, **not** in the config.

Does that make sense to you?

**Comment by JoeRu** [comment]
> My initial suggestion was to move the latex package relevant configs to a subdirectory of config, to be included on demand only, but that violates the design principle that all configuation items should have an initial value (i.e., the keys must be present in the config hash). And it turned out that's not the real problem.
> 
Got that; 

> Currently, you have three kinds of definitions in the LaTeX part of the config.
> 
> First, the names of the templates. This is okay, people may want to customize the way their songs are rendered. This is similar to the styles files in the HTML output settings.
> 
> Second, the template search path. This should be preset to `[ ]`. In the code, please add (prepend) the elements of $ENV{CHORDPRO_LIB} with `/templates` appended so the user can have her own set of templates.
> 

That's fine with me; Having it empty is ok.

> Third, package-specific definitions for some LaTeX items. These are not independently configurable. I know that you want to abstract out much of the details but these simply do not belong in the configs. For example, the beginchorus_tag is `"\\beginchorus"`. This macro is defined in the LaTeX 'song' package which is included in `songbook.tt`. If I were to use the 'songbook' package I need to provide an alternative `songbook.tt` but I would **also** need to change the definition of beginchorus_tag to `"\\begin{SBChorus}"`etc. So the proper place to define these is in `songbook.tt`, **not** in the config.
> 
> Does that make sense to you?

This is sort of more problematic (and i don't go for the general approch way here); Some things can be handled in a template - some not. I made a example of a `guitar_latex.json` in this PR - maybe you can see the details of the problem about it by comparing the `songbook_latex.json` with the `guitar_latex.json`.

Per sé - i would agree and let everything handled in the template-Engine - but this would require more logic in the templates - - that would handle it 'unhandy'. So i understand you're problem.

From my perspective it's more a lexigraphical problem (my lex times... oh-my-god). Some of the packages need to now - what's happening on what point of time - others don't. This makes it neccessary to put out the lex-points of Chordpro for config; 
Other lexigraphical units like the songbook or the song - are a bit to 'big' and have therefore a template.

So - from my perspective - the config-items (besides the path) belong to a chordpro-grammar (lex - yacc like) - that needed output handling.

.. i really would love to discuss this on a beer or coffee - than here. Maybe on a video-call -not that cool - i know...

**Comment by sciurius** [comment]
Thanks for the changes. The `guitar_songbook.tt` makes it clear why you want the Template approach. However, 
comparing `songbook_latex.json` with `guitar_latex.json` precisely shows why these definitions should not be in the config.

As I see it, LaTeX packages 'song' and 'guitar' need different code (LaTeX macros) to e.g. start a chorus.
The actual package selection is done in `songbook.tt`. So the correct place to put the chorus-starting code is in `songbook.tt`.
This way you can keep the definitions consistent with the package. Putting it elsewhere, in another file, would be confusing since the user then has to maintain consistence between separated pieces of information.

Have you considered Template variables? For example, in `songbook.tt`:

    [% set beginchorus_tag = "\\beginchorus" %]

You can fetch the values in the perl code from the Template stash.

You could even move the contents of `image.tt`, `song.tt` and `comment.tt` to `songbook.tt` (as BLOCKs) so you end up with one single self-contained Template file that has all the information needed. But that's a matter of taste.

You know backends have their own command line options? Using `--backend-option` (or `--bo` for short) you can pass information directly to the backend. This is used e.g. by the ChordPro backend, that supports choosing between plain ChordPro output, and the MobileSheetsPro variant (subset) of ChordPro. This may be interesting for the LaTeX backend as well, to select between the 'song' package or the 'guitar' package etc.

**Comment by JoeRu** [comment]
.. hmm ...
i see the point - sort of.

there are some nuts to crack so -
1. The obligatory variables for the templates needed to be clear - because - otherwise the template engine will fail. But that’s more an documentation issue – then an technical one.
2. some variables are set within the output-module - so here it would be necessary work with symbols – or template code (st. like ` [% begin_of_chorus %]`) – I need to test that.
3. I would need to make the variables that are given to template much more transparent.
It’s sort of the `$s` - which is very present over all outputs. 


I will check this approach. But as this is a bigger redesign – can we make this a next version release please?

**Comment by JoeRu** [comment]
ok - that was much easier then assumed.The last commit moves the obligatory variables to the template and removes it out of the default config. Examples are not enhanced.
The song template is removed – comment and especially image - I like to evaluate – these are a bit special in handling – but I’m happy to keep them – it’s usage is clear.

**Comment by sciurius** [comment]
Great to hear that it wasn't that hard.
I see you took the approach of emitting `[% beginchorus_tag %]` etc. Simple and effective. Alternatively you could fetch the values directly from the Template stash. Well, maybe later.

Some minor points:
In songbook_latex.json and songbook_guitar.json, you include `guitar`. Is that necessary? This file is already included by default in the main config.
In songbook_latex.json and songbook_guitar.json, please remove `template_include_path` since that is already handled by the main config.
In LaTeX.pm, please add `$CHORDPRO_LIBRARY` to the `INCLUDE_PATH` as discussed earlier.

Would it be more intuitive to group the template settings? E.g.
````
"LaTeX" : {
    "template_include_path" : [ ],
    "templates" : {
        "songbook" : "songbook.tt",
        "comment" : "comment.tt",
        "image" : "image.tt",
     },
}

````

**Comment by JoeRu** [comment]
yep - no problem; Adapted as requested.
The config needed to set `$CHORDPRO_LIBRARY` into "" - i don't know if this work as suspected.

**Comment by JoeRu** [comment]
ok; got what you meant - and where to set `$CHORDPRO_LIBRARY`

Here is a result of the following commands [guitar-pdf](https://web-dreamer.de/wp-content/uploads/2022/03/test2.pdf) and [songbook-pdf](https://web-dreamer.de/wp-content/uploads/2022/03/test.pdf)

```
perl script/chordpro.pl --config=lib/App/Music/ChordPro/res/config/songbook_latex.json test_1.cho -o ./test.tex 
perl script/chordpro.pl --config=lib/App/Music/ChordPro/res/config/guitar_latex.json test_1.cho -o ./test2.tex 
```

Test test_1.cho is mainly the basic-test-file - but i needed an image to check the settings.

**Comment by sciurius** [comment]
Please apply this patch to fix the html tests failures.

[htmlverse.patch.txt](https://github.com/ChordPro/chordpro/files/8379234/htmlverse.patch.txt)

**Comment by sciurius** [comment]
Please apply this path to complete the config changes.

I'd advise to use config item`"latex"` in lowercase to avoid confusion.

[config.patch.txt](https://github.com/ChordPro/chordpro/files/8379382/config.patch.txt)

**Comment by JoeRu** [comment]
finaly - all passes :)

**Comment by sciurius** [comment]
Good progress. Unfortunately I still get test errors:

````
t/74_latex.t .. # Testing 2 cho files
# Files latex/30_cho_1.tmp and latex/30_cho_1.tex differ at line 7
#   <  
#   >  D XX0232

not ok 1 - latex/30_cho_1.cho
````
Same for the other tests. It seems that the chord lines do not come out. I looked at the code but could not see amything wrong. Can you?

Also, can you add the LaTeX related files to MANIFEST?

Thanks, Johan

**Comment by JoeRu** [comment]
Hi Johan,
i did update the MANIFEST file; 
The tests from my branch (and here from the automated test) are fine.  So i guess there is some diff in your branch.

Yours
Johannes

**Comment by JoeRu** [comment]
I guess you have a diff at `t/latex/t_songbook.tt `-> most propably at this line - line 30 (is missing ) :

```
[%  FOREACH chord IN song.chords %][% chord.chord %] [% chord.frets %]
```

**Comment by sciurius** [comment]
All the test programs (t/71_cho.t, t/72_mma.t, t/73_md.t, ...) call the ChordPro core with first argument `--no-default-configs`.

There's a reason for that ☺.

Also, please remove the unnecessary things like decoda and test groove from 73_md.t and 74_latex.t .

**Comment by sciurius** [comment]
Have you considered writing the templates a bit like this? Seems more elegant and maintainable to me.
[t_songbook.tt.txt](https://github.com/ChordPro/chordpro/files/8409194/t_songbook.tt.txt)

**Comment by JoeRu** [comment]
> Have you considered writing the templates a bit like this? Seems more elegant and maintainable to me. [t_songbook.tt.txt](https://github.com/ChordPro/chordpro/files/8409194/t_songbook.tt.txt)

well - no - didn't occur to me; I tested a bit - and it works - next time ;)

**Comment by sciurius** [comment]
Hi Joe,
As far as I can see everything is fine now.
After the merge I want to remove the requirement for Template from Makefile.PL since I do not want to trouble all users for something that only few will actually use.

Thanks for your contributions!

**Pull request merged**
