### PR TITLE
Extend grid directive

### PR DESCRIPTION
**Pull request by bublath**
Add the ability to overwrite the default grid placing by song.
One potential use case:
While placing the diagrams on "right" makes sense for most songs, it reduces horizontal space for multi-column songs significantly, so users might want to exceptionally place the diagram on the bottom for these songs only.

### CODE REVIEW

**Comment by sciurius** [comment]
As discussed, this is not to be controlled by the song with a directive, but should be dealt with in the associated config (just like choice to place chord diagrams at the right).

**Comment by bublath** [comment]
I'm not sure I follow your argument here. Why is it ok to remove the grid individually per song {no_grid} , change the fonts and do many other things that impact the design very significantly, but not ok to choose where the grid is placed?
In my current 100 song book, I have two pages where my default (grid to the right) messes up the layout due reduced horizontal space. Without this (very unintrusive) option to move the grid to the bottom, I would need to totally redesign them (probably resulting in 2 pages instead of 1 page) or at least completely remove the grid.
I believe many users could find this useful and it is totally backwards compatible and just extends the existing grid command to optionally specifiy "how".

**Comment by sciurius** [comment]
Several reasons. First of all, `{grid}` and `{no_grid}` are legacy directives and their use is discouraged. Changing fonts etc with directives is also legacy and also encouraged. Augmenting discouraged directives with new features would be wrong.
Also, as I wrote before, it violates the separation of content and appearance. Now I'm not saying that that is cast in stone, but at least we can try.
In your case, you use a modern3 style with 2 columns. In this particular combination, the diagrams at the right get (sometimes) in the way so you want to move them to the bottom. If I were to use your song in a modern3 single-column style, I would still get the diagrams at the bottom. For no reason. It takes a bit of fun out of sharing song files.

> Without this (very unintrusive) option to move the grid to the bottom, I would need to totally redesign them (probably resulting in 2 pages instead of 1 page) or at least completely remove the grid.

For this there are song specific config files. Just create two configs named after the song files, and content
````
{ "pdf" : { "diagrams" { "show" : "bottom" } } }      (json)
pdf.diagrams.show:bottom                              (prp)
````
and you're good to go.

If you insist on dealing with this in the song file, you can use the undocumented and formally unsupported directive
````
{+pdf.diagrams.show:bottom}
````

**Comment by bublath** [comment]
Need to try that song specific configs - sounds like a possible solution.

IMHO it still makes it more complicated than necessary. You're replacing something that is convenient and user friendly with a more complex approach.
On your argument about sharing song files: When getting a song file from another source and using your individual configuration, you will never be happy with the layout. Since your individual json will change fonts, spacings, margins ... you will end up having different line breaks, things won't fit into the page etc. and you end up reworking the file anyway. (I'm going thru that process migrating from chordii to chordpro even though I try to keep the layout pretty similar).
Thus I see no harm in having those inline directives and letting the users chose if they want to use them or not. Deprecating them will break many songbooks and user will complain.
 
I get what you try to achieve, though maybe it should be a general debate with users, if it really is what they expect.
Personally, I'd rather have one json config file that gives me a good base configuration and then do some specific tweaks in the songfile if necessary (and no clutter with additional files). But that's my opinion - maybe I'm the only one.

**Comment by sciurius** [comment]
You'll find song specific configs more than interesting.
If you use a file list, you can even specify (additional) configs in the file list, e.g.
````
song1.cho
song2.cho --config=chordsbottomplease.json
song3.cho
```

**Comment by bublath** [comment]
Closing as approach is not supported by owner

**Comment by sciurius** [comment]
Thanks.
Did you experiment with the song-specific config files?

**Comment by bublath** [comment]
Frankly no. I decided to continue using my branch for now, as it currently contains all the functionality/fixes that I need.
I rebased it with your latest dev and cherry-picked my patches into my fork of dev at
https://github.com/bublath/chordpro/tree/dev

**Pull request closed without merging**
