### PR TITLE
suppressed-chord-diagrams feature

### PR DESCRIPTION
**Pull request by bublath**
Add feature for suppressing "easy" chords like chordii did.
Default is to suppress none, except when using --config=chordii , then the easy chords that chordii has used will be suppressed.
See issue #242 
Users need to define individual lists in json using settings->suppressed-chord-diagrams

### CODE REVIEW

**Comment by sciurius** [comment]
Thanks for the PR. You (correctly) assumed that providing working code helps to get your feature request implemented.

Before getting into details a teaser question: What happens (and, what is _supposed_ to happen) when the user enables transcoding?

**Comment by bublath** [comment]
Tricky question as I can't really imagine what someone using this would expect (I don't even use "german" trancode)
I'm torn between two options:
1. Using $i->{name} instead of $i->name for the test, so a "G" is still suppressed even if it's now called Sol as it's still the same grid that was considered "easy"
2. Keep as is, so someone familiar using the transcoded chords, should actually also put them in the list as e.g. "Sol". I feel that this would be more consistent, as you might wonder why your "Sol" disappeared while you put "G" in the list.

**Comment by sciurius** [comment]
Another thing to consider: Suppressing chords is not really related to PDF output. Other backends may want to play along.
If you take a look at ChordPro/Song.pm, somewhere around line 450 and on, you can see how the list of used chords is constructed.

**Comment by bublath** [comment]
Only took a quick look. You mean something like setting is_nc in @used_chords?

**Comment by bublath** [comment]
Ok, I think I got it. I just removed them right away from @used_chords before there is further processing. That should work for all formats, doesn't it?

**Comment by bublath** [comment]
I have another PR ready that extends the {grid} directive so you can also do something like {grid:bottom} which I found helpful for 2-column songs, where "right" playing makes the columns to narrow (so I overwrite it with "bottom") while I like to use "right" for the rest of the book.
I was waiting for this PR to get merged before I submit that - or should I just combine here , so you can review it in on go?

**Comment by sciurius** [comment]
I must admit that I do not have the faintest idea what you mean. Can you elaborate?

As for combining PRs I think it is best to keep separate changes in separate PRs.

**Comment by bublath** [comment]
Sure. Will put the other thing as separate PR, that should make it clearer. Any further comment on this one?

**Comment by bublath** [comment]
Unfortunately this current PR is on my master. I created a branch for the grid topic on https://github.com/bublath/chordpro/tree/grid_directive
but it naturally includes this PR already, so it will have to go one after the other.
It's just 2 lines and extends {grid} so it can define the diagram placing e.g. by {grid:bottom} (overwriting the default behaviour per song)

**Comment by sciurius** [comment]
I've augmented some of your code to deal with transposition and transcoding. I'll check in later today.

**Pull request closed without merging**
