### PR TITLE
(website) Update landing suggestion

### PR DESCRIPTION
**Pull request by Desbeers**
- Consistent displaying of ‘ChordPro’
- Shorter ‘statement’
- Fixed HTML validator warnings
- Cleaned document source; easier to read and adjust
- Added ‘favicon’

### CODE REVIEW

**Comment by sciurius** [comment]
Nice.

How is the SEO?

**Comment by Desbeers** [comment]
Pretty ok I think. It has a  good structure and also a title now ;-)

Meta stuff but also well-named sections in its body source.

**Comment by sciurius** [comment]
SEO is a little bit more than that... The current landing page has almost 100 lines of SEO information...

**Comment by Desbeers** [comment]
It does not; I looked at the source. It does not even have a *real* title; mostly useless *meta* information. And besides that; search engines are also smarter nowadays. A good structured source will give you the best result. That is why I gave most 'div's an id or a class. I know about this stuff.

**Pull request merged**
