### PR TITLE
Update link to Emacs mode

### PR DESCRIPTION
**Pull request by josephmturner**
Howard Ding is happy for me to maintain Emacs ChordPro mode:

https://github.com/hading/chordpro-mode/issues/5#issuecomment-1503359015

### CODE REVIEW

**Comment by sciurius** [comment]
Thanks for taking over support of chordpro-mode!

Chordpro mode was originally intended to be used with the chord (chordii) tool, which has been superceded for a while now by the modern ChordPro. I've forked chordpro-mode in 2015 and made some small changes. It would be nice to consolidate our changes.

https://github.com/sciurius/chordpro-mode.git .

**Comment by sciurius** [comment]
Merged into the 'dev' branch.

**Comment by josephmturner** [comment]
Hi Johan! I went over your fork and consolidated the changes. Please take a look at the latest master branch on my fork.

In summary,

- I cherry-picked two commits from your branch.
- I changed the default binding for `chordpro-insert-chord` to `[` (similar behavior to your "hot-insert" function).
- The `chordpro-export` function in my fork takes a `.cho` file and converts it to a `.pdf`. I didn't not incorporate any changes related to a2crd. What is a2crd for?
- All other improvements made on your fork have the same or similar improvement on mine.

**Comment by sciurius** [comment]
Thanks!

Entering a chord `a/b` yields `A/b`. The bass should be uppercased as well.

In my 'hot' entry, `]` is set up to terminate minibuffer input, so I can enter a chord blindy by typing `[A]` instead of `[A <enter>`.

The `a2crd` functionality converts a region with chords on top of the lyrics text (e.g. from Ultimate Guitar) to ChordPro (chords embedded in the lyrics). No problem if you don't want to add this, I'll add it to my customizations.

**Comment by josephmturner** [comment]
> Entering a chord `a/b` yields `A/b`. The bass should be uppercased as well.

Good catch! I came up with a better solution using a special `syntax-table`. Is it working now?

> In my 'hot' entry, `]` is set up to terminate minibuffer input, so I can enter a chord blindy by typing `[A]` instead of `[A <enter>`.

If this is important to you, I am willing to look into a clean way to switch the keymap during a single completing-read call. Would you be willing to try out the new behavior `[A <enter>` to see if you get used to it?

> The `a2crd` functionality converts a region with chords on top of the lyrics text (e.g. from Ultimate Guitar) to ChordPro (chords embedded in the lyrics). No problem if you don't want to add this, I'll add it to my customizations.

Thanks for explaining! `a2crd` sounds very useful! Check out the new `chordpro-a2crd` function. I noticed that chords copied from Ultimate Guitar have an extra newline between chords and lyrics, so with a prefix argument `chordpro-a2crd` will delete blank lines before attempting to convert to ChordPro format.

**Comment by sciurius** [comment]
> Good catch! I came up with a better solution using a special `syntax-table`. Is it working now?

Yes, looks okay now.

> If this is important to you, I am willing to look into a clean way to switch the keymap during a single completing-read call.

It's all in my version already...

> Would you be willing to try out the new behavior `[A <enter>` to see if you get used to it?

No. Using &lt;enter&gt; was the original behaviour and I modified it to use `]` since that is most intuitive. And it is the way you type ChordPro in other tools. Personally I seldom look at the minibuffer, I mainly take advantage of the automatic capitalisation.

It is okay if you don't want to change this behaviour - I'll just override the function in my `.emacs`. But it would be a missed opportunity. Also, it doesn't clash with the current behaviour.

> Check out the new `chordpro-a2crd` function. 

Great! Thanks.

**Comment by josephmturner** [comment]
> Personally I seldom look at the minibuffer, I mainly take advantage of the automatic capitalisation.

Your comment gave me an idea! Please take a look at the latest version of `chordpro-mode.el`, which binds `]` to a function that closes AND normalizes the chord at point without opening the minibuffer. Hopefully this is a happy compromise. Feedback welcome :)

**Comment by sciurius** [comment]
Looks nice, I'll try it for a while.

A suggestion: the lisp functions to move a chord forward/backward are called `chordpro-transpose-chord` and `chordpro-transpose-chord-backward`. I suggest changing these names since 'transpose' means something different.

**Comment by josephmturner** [comment]
> A suggestion: the lisp functions to move a chord forward/backward are called `chordpro-transpose-chord` and `chordpro-transpose-chord-backward`. I suggest changing these names since 'transpose' means something different.

Good idea. Done.

**Comment by josephmturner** [comment]
@sciurius thank you!!

**Comment by sciurius** [comment]
When entering a chord with a bass note, the latter is not upcased.

E.g. `[c/b]` gives `[C/b]` but should result in `[C/B]`.

**Comment by josephmturner** [comment]
@sciurius Thanks for reporting this bug! Fixed on master.

**Comment by sciurius** [comment]
A suggestion: a key that prompts for a section and inserts `{start_of_` _section_ `}`, and a key that closes any open section with `{end_of_` _section_ `}`

**Comment by josephmturner** [comment]
@sciurius Good idea! Are there are environment directives besides the following?

- `chorus`
- `verse`
- `bridge`
- `tab`
- `grid`
- `abc`
- `ly`

**Comment by sciurius** [comment]
There are predefined (known) sections:

    bridge
    chorus
    grid
    tab
    verse

But you can use anything you want. If you open a section with `start_of_foo` then ChordPro tries to use a delegate (similar to `abc` and `ly`). If there's no delegate the new section is basically equivalent to `verse`. 

What I had in mind was a key that prompts for a section name (i.e. arbitrary input) and uses that for `start_of_...`. The other key just closes any open section.

**Comment by josephmturner** [comment]
@sciurius  Check out the new command `chordpro-insert-environment-directive`, which uses `completing-read` under the hood. You can enter arbitrary input if you like, but it offers completion for the predefined environment directives. You can also customize the completion options with `chordpro-environment-directives`.

**Comment by sciurius** [comment]
Real nice! Inserting both the start and end reduces the need for a 'close open environment' command.

**Comment by josephmturner** [comment]
@sciurius Thanks :)

**Pull request merged**
