### PR TITLE
Workflow to generate and upload appimage

### PR DESCRIPTION
**Pull request by lpinner**
GitHub action workflow to generate appimage and upload as release asset when a release is tagged.

### CODE REVIEW

**Comment by lpinner** [comment]
Completed workflow showing successful run - https://github.com/lpinner/chordpro/actions/runs/8550106249/job/23426532959

Output asset from dummy release - https://github.com/lpinner/chordpro/releases/tag/D6.050-7

**Comment by sciurius** [comment]
Great, thanks!

**Comment by sciurius** [comment]
I think most logical is:
* default TARGET is wxhcordpro
* if started with 1st arg = chordpro (or wxchordpro) → set TARGET to chordpro (wxchordpro)
* else, if there's an executable target that corresponds to the basename of the actual file name, set TARGET
* run TARGET


````
#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
TARGET=wxchordpro
BINARY_NAME=$(basename "$ARGV0")
export LD_LIBRARY_PATH=$HERE:$LD_LIBRARY_PATH
export APPIMAGE_PACKAGED=1.00

if [ "$1" = "chordpro" -o "$1" = "wxchordpro" ]; then
    TARGET=$1
    shift  # remove first arg

elif [ -e "$HERE/$BINARY_NAME" ] ; then
    TARGET="$BINARY_NAME"
fi

exec ${HERE}/"$TARGET" ${1+"$@"}
````

**Comment by lpinner** [comment]
I didn't realise my dummy release tags for testing the workflow would come through in this PR. Sorry about that. You can delete them from the [tags page](https://github.com/ChordPro/chordpro/tags).

**Pull request merged**
