### PR TITLE
Add chord definitions for keyboards.

### PR DESCRIPTION
**Pull request by nomike**
As discussed in #237 I added chord definitions for all common chords.
I used https://www.pianochord.org/c.html as a source.

It needs some tweaking though as I'm getting the following errors:
```plaintext
test.cho", line 4, Unknown chord: "CmM7"
	[C][Cm][C7][Cm7][Cmaj7][CmM7][C6][Cm6][C6/9][C5][C9][Cm9][Cmaj9][C11][Cm11][C13][Cm13][Cmaj13][Cadd9][Cadd2][C7-5][C7+5][Csus4][Csus2][Cdim][Cdim7][Cm7b5][Caug][Caug7]
"test.cho", line 4, Unknown chord: "C6/9"
	[C][Cm][C7][Cm7][Cmaj7][CmM7][C6][Cm6][C6/9][C5][C9][Cm9][Cmaj9][C11][Cm11][C13][Cm13][Cmaj13][Cadd9][Cadd2][C7-5][C7+5][Csus4][Csus2][Cdim][Cdim7][Cm7b5][Caug][Caug7]
"test.cho", line 4, Unknown chord: "Cm13"
	[C][Cm][C7][Cm7][Cmaj7][CmM7][C6][Cm6][C6/9][C5][C9][Cm9][Cmaj9][C11][Cm11][C13][Cm13][Cmaj13][Cadd9][Cadd2][C7-5][C7+5][Csus4][Csus2][Cdim][Cdim7][Cm7b5][Caug][Caug7]
"test.cho", line 4, Unknown chord: "C7+5"
	[C][Cm][C7][Cm7][Cmaj7][CmM7][C6][Cm6][C6/9][C5][C9][Cm9][Cmaj9][C11][Cm11][C13][Cm13][Cmaj13][Cadd9][Cadd2][C7-5][C7+5][Csus4][Csus2][Cdim][Cdim7][Cm7b5][Caug][Caug7]
"test.cho", line 4, Unknown chord: "Caug7"
	[C][Cm][C7][Cm7][Cmaj7][CmM7][C6][Cm6][C6/9][C5][C9][Cm9][Cmaj9][C11][Cm11][C13][Cm13][Cmaj13][Cadd9][Cadd2][C7-5][C7+5][Csus4][Csus2][Cdim][Cdim7][Cm7b5][Caug][Caug7]
"test.cho": No chord diagram defined for "C6/9", "C7+5", "Caug7", "Cm13" and "CmM7" (skipped)
```

Example: 
[piano.tar.gz](https://github.com/ChordPro/chordpro/files/9276947/piano.tar.gz)

It's not entirely clear to me how you internally do the mapping between "Cm" written in the cho-file and "C-" defined in the source.
I guess at this place you also need to define that there could be a "aug7" chord and the others id doesn't recognize.

I used "-7" at the beginning, but it didn't work either, so I tried "m7" instead, which worked. This feels quite inconsistent.

But I guess that's not too hard for you to fix as you are more familiar with your source code.

And one thing which is visible in the generated PDF is how the chords overflow the diagrams. But that's a different bug I assume,

### CODE REVIEW

**Comment by sciurius** [comment]
The chords parser canonicalizes chord names to an internal form. This includes translation of `m` to `-` and `aug` to `+`.
The table we are dealing with here is an internal table, hence the discrepancy with the external form that uses `m` and `aug` etc.
Can you incorporate these changes?
Also, I think a more common way to write minor major7 is `-maj7`.

**Comment by nomike** [comment]
Ahh. Im getting closer.

So the stuff I add [here](https://github.com/nomike/chordpro/blob/dev/lib/App/Music/ChordPro/Chords.pm#L511) has an influence on PDF generation.
So if I remove everything, I get a couple of these errors:

```plaintext
PDF: No diagram for chord "Cm6"
```
These errors however

```plaintext
"test.cho", line 4, Unknown chord: "C6/9"
```

are not related that that %keys dictionary. No matter what I put in there, I'm getting this for several chords.

I've updated the dictionary and pushed it to my github repository, as you requested.

To get rid of those unknown chord errors though, I guess the parser needs some tweaking and bugfixing.
I can have a look, but I'm having a hard time with those perl specific syntax features ($var, %var, etc.) as I'm mainly programming in python. You might be more efficient with that.

**Comment by nomike** [comment]
I found where to fix it in the parser.pm, isn't that complicated after all.
Expect some commits from me in the next 20-30 minutes.

**Comment by nomike** [comment]
I fixed some issues in Chords.pm and extended Parser.pm to support the missing chords.
I guess parsing C6/9 could be an issue when the parser is looking for slash chords.

Thus I replaced it with "C6add9" which according to this [pianochord.org](https://www.pianochord.org/c6-9.html) is a valid way of writing it too.

My updated test song now converts without errors or warnings:
[piano.tar.gz](https://github.com/ChordPro/chordpro/files/9277541/piano.tar.gz)

**Comment by nomike** [comment]
BTW: You might want to add "MYMETA.json" and "MYMETA.ym" to .gitignore. They pop up as untracked files after a "sudo make install".

**Comment by nomike** [comment]
I added some more chord definitions. This covers all songs currently in my songbook.
However, there are many many more.

I found another page which lists a huge amount of them:
https://www.scales-chords.com/chord-database/piano/C/

Maybe it makes sense to auto convert the stuff on that page.
But I guess how a chord works might follow some logic, so maybe we can avoid having a hard-coded list after all and generate those definoopns on the fly?

**Comment by sciurius** [comment]
ChordPro's idea has always been to support a reasonable collection of common chords, and make it possible for the user to add uncommon ones. Supporting all chords is impossible, since the collection of chords is practically unlimited.
I think with your additions we support far more than 'a reasonable collection of common chords' ☺.

**Pull request merged**
