### PR TITLE
Update Markdown-Output / redesign

### PR DESCRIPTION
**Pull request by JoeRu**
This is a rather small -PR- with probably only small impact; In Latex - and in Markdown i recognized that verses are - when not explicit set - not functional. A songline should not be without context;  So if no Context is set - i asume it's part of a verse. If `begin_of_verse` / `end_of_verse` is set - structurize should not run into this assumption at all.

### CODE REVIEW

**Comment by JoeRu** [comment]
The Markdown-Layout isn't working for Markdown.pm. This is rather - a problem of the Layout-class. It's also sense-less - it's only used within the songlines (where no markdown-specific-layout can take place. I would suggest to put back the text-layout as i originaly put it in.

**Comment by sciurius** [comment]
Long time ago, when I was working on the HTML and LaTeX backends, I tried to 'enhance' ChordPro into 'Structured ChordPro', where all song lines needed to be within a context. You can still see it in the source (the `structurize` calls). At the time I stopped with the structurize approach since it caused some problems that I didn't felt like solving at the time.

IIRC, the problems were with empty lines and comments. Assume you have
````
# an empty line

{c: A comment}
[A]Hello, [Bm]World!
````
Are the empty line and the comment part of the implied verse context, or not. In other words, is it:
````
{start_of_verse}

{C: A comment}
[A]Hello, [Bm]World!
{end_of_verse}
````
or
````
{start_of_verse}

{end_of_verse}
{start_of_verse}
{C: A comment}
{end_of_verse}
{start_of_verse}
[A]Hello, [Bm]World!
{end_of_verse}
```

I'm open to restarting this approach provided the issues are solved.

**Comment by sciurius** [comment]
> The Markdown-Layout isn't working for Markdown.pm. This is rather - a problem of the Layout-class. It's also sense-less - it's only used within the songlines (where no markdown-specific-layout can take place. I would suggest to put back the text-layout as i originaly put it in.

Please take this to a separate issue.

**Comment by JoeRu** [comment]
ok; I put in Markdown-Layout (tested with newest git-repo - it did not through warnings) and commented Verse-Context out. 

On the Song-Verse-Context; Give it a thought. On Markdown and on LaTeX - i will assume a songline is verse if no context is given - these lines of code can be output-specific.
 
Put it as i said: Its a design-decision - what wants chordpro be. A less better formatting option (then for example LaTeX) - or a simplified Guitar-Sign-Language; I would suggest - keep it simple as it is - and leave complex formatting to other tools. 

The output basis gives plenty of options - for further tools to work on the output. And the original PDF Output is pretty good; Those who want to manage the last mm can go with LaTeX in near future.

**Pull request closed without merging**
