### PR TITLE
WIP: Add Dockerfile

### PR DESCRIPTION
**Pull request by andb0t**
This is work in progress. **Don't merge, yet!**

Feel free to try it though. Simply follow the instructions in the `README.md`.

### CODE REVIEW

**Comment by andb0t** [comment]
Until now, files cannot be passed to chordpro inside the container, yet. This needs to be fixed. Working on it and going to update soon. I'll remove the "WIP" tag, once it's ready and link you for review.

**Comment by ChordPro** [comment]
````
 % docker build -t chordpro .
Sending build context to Docker daemon  23.09MB
Step 1/9 : FROM perl:5.20
5.20: Pulling from library/perl
Image docker.io/library/perl:5.20 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
8b87079b7a06: Pull complete 
a3ed95caeb02: Pull complete 
1bb8eaf3d643: Pull complete 
3e04171ce2e5: Pull complete 
0b73d3fea769: Pull complete 
ffb34b57cdf2: Pull complete 
8eeaf71aee14: Pull complete 
72cfc9cbff48: Pull complete 
2d693787a8c5: Pull complete 
Digest: sha256:5e06bbcf01ed88d6812839bcc7645a3960361a6843e14b6337de2897dfb2863f
Status: Downloaded newer image for perl:5.20
 ---> bbe5a82c1dbe
Step 2/9 : RUN apt-get install bash
 ---> Running in 130072433e43
OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown
Exit 1
````

**Comment by sciurius** [comment]
See https://github.com/ChordPro/chordpro/issues/124#issuecomment-726731444

**Comment by andb0t** [comment]
> 
> 
> ```
>  % docker build -t chordpro .
> Sending build context to Docker daemon  23.09MB
> Step 1/9 : FROM perl:5.20
> 5.20: Pulling from library/perl
> Image docker.io/library/perl:5.20 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
> 8b87079b7a06: Pull complete 
> a3ed95caeb02: Pull complete 
> 1bb8eaf3d643: Pull complete 
> 3e04171ce2e5: Pull complete 
> 0b73d3fea769: Pull complete 
> ffb34b57cdf2: Pull complete 
> 8eeaf71aee14: Pull complete 
> 72cfc9cbff48: Pull complete 
> 2d693787a8c5: Pull complete 
> Digest: sha256:5e06bbcf01ed88d6812839bcc7645a3960361a6843e14b6337de2897dfb2863f
> Status: Downloaded newer image for perl:5.20
>  ---> bbe5a82c1dbe
> Step 2/9 : RUN apt-get install bash
>  ---> Running in 130072433e43
> OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown
> Exit 1
> ```

Oh, I can't reproduce this. Let's postpone fixing it until we have found a way to avoid the container mount.

**Pull request closed without merging**
