### PR TITLE
Adds method to sort the song book and align 2-page songs for booklets

### PR DESCRIPTION
**Pull request by bublath**
- Sorting by title or author
- Align 2-Page songs, so they are fully visible without turning a page be switching songs or adding empty pages

### CODE REVIEW

**Comment by sciurius** [comment]
Nice.
Please do not set your tabs to 4 spaces. In Config.pm, do not use leading tabs in the json section, only spaces.
Please pull in the latest dev.

I used the attached test song.
[song.zip](https://github.com/ChordPro/chordpro/files/14430302/song.zip)

````
$ perl script/chordpro.pl -X songs.cho --csv --no-toc --def pdf.sort-pages= && cat songs.csv
title;pages;sort title;artists;composers;collections;keys;years
BBBBB;1;;;;;;
AAAAA;3-4;;;;;;
AAAAA;5-6;;;;;;
ZZZZ;7-8;;;;;;
EEEE;9;;;;;;
POPPP;11-12;;;;;;
````
Good.

````
$ perl script/chordpro.pl songs.cho --csv --no-toc --def pdf.sort-pages=title && cat songs.csv
title;pages;sort title;artists;composers;collections;keys;years
AAAAA;1-2;;;;;;
AAAAA;3-4;;;;;;
BBBBB;5;;;;;;
EEEE;7;;;;;;
POPPP;9-10;;;;;;
ZZZZ;11-12;;;;;;
````
Nice.

````
$ perl script/chordpro.pl songs.cho --csv --no-toc --def pdf.sort-pages=2page && cat songs.csv
title;pages;sort title;artists;composers;collections;keys;years
BBBBB;1;;;;;;
AAAAA;4-5;;;;;;
AAAAA;8-9;;;;;;
ZZZZ;12-13;;;;;;
EEEE;15;;;;;;
POPPP;18-19;;;;;;
````
Now the odd-page songs start on a right page (ok) and the even-page songs start on an even page.
However, there are two empty pages before each even-page song.

````
$ perl script/chordpro.pl songs.cho --csv --no-toc --def pdf.sort-pages=2page,compact && cat songs.csv
BBBBB;1;;;;;;
AAAAA;4-5;;;;;;
AAAAA;8-9;;;;;;
ZZZZ;12-13;;;;;;
EEEE;15;;;;;;
POPPP;18-19;;;;;;
````
Apart from the two empty pages before each even-page song, I would expect the one-page song EEEE te move before an even-page song.

Am I missing something?

**Comment by bublath** [comment]
The compact mode conflicts with pagealign-songs. You need to set pagealign-songs to 0, otherwise pagealign-songs adds an empty page and compact therefore needs to add another one. Any suggestion how to resolve?
E.g. I could do
	# Align.
	if ( $ps->{'pagealign-songs'} && !($page % 2) && !$ps->{'sort-pages'}=~ /compact/) {

With that patch or setting pagealign-songs to 0, "2page,compact" gives me
BBBBB;5;;;;;;
AAAAA;6-7;;;;;;
AAAAA;8-9;;;;;;
ZZZZ;10-11;;;;;;
EEEE;12;;;;;;
POPPP;14-15;;;;;;

Which is correct. As the last song is a 2 page song, it cannot pull in any 1 page song and thus needs to add the empty page 13

If I change your second "AAAAA" song to have only one page, it pulls in "EEEE" to fill the gap
BBBBB;5;;;;;;
AAAAA;6-7;;;;;;
AAAAA;8;;;;;;
EEEE;9;;;;;;
ZZZZ;10-11;;;;;;
POPPP;12-13;;;;;;

**Comment by sciurius** [comment]
I already suspected something like that.
It seems that ignoring `pagealign-songs` should be done with `2page` and `compact`.
Is `compact` a real modifier (i.e., it must be `2page,compact`) or can it be used standalone (i.e. `compact` implies `2page`)? If it can be used standalone the proposed test becomes slightly more complex:
````
if ( $ps->{'pagealign-songs'} && !($page % 2) && !$ps->{'sort-pages'}=~ /(2page|compact)/) {
````

Attached a test program.
[test.zip](https://github.com/ChordPro/chordpro/files/14432279/test.zip)

**Comment by sciurius** [comment]
I cloned your repo and had no difficulties with `git pull`. But I know from experience that sometimes git can be surprising.

Your code looks nice and clean, I can take it over and merge manually if you want.

**Comment by bublath** [comment]
that would be appreciated. I just pushed the Config.pm cleanup and some cleanup in the PDF.pm - you can take it from there :)

**Comment by sciurius** [comment]
The changes are in. Please verify and close this PR.

I'm not sure why the progress information is written to standard output. Shouldn't this be standard error?

**Comment by bublath** [comment]
Looks good. My test songbook compiles and looks correct. 
To me it was not important where the output was written to.
If you prefer STDERR - I just tested that changing all "print" -> "print STDERR" and all "STDOUT->flush()" -> "STDERR->flush()" works as well

**Comment by sciurius** [comment]
Under certain circumstances the PDF output can be written to standard output, and we don't want to have progress data garbling up the PDF. I'll change it.

**Comment by bublath** [comment]
Closing as changes were manually merged by sciurius

**Comment by sciurius** [comment]
One final thing: I know you use {st:} for authors, but we do have a real {author:} directive. To avoid confusion, I suggest to change 'author' to 'subtitle'. Ok?

**Comment by bublath** [comment]
Sure, no problem

**Pull request closed without merging**
